### ISSUE TITLE
DB hosting: what do we need and what will it cost?

### ISSUE THREAD

**Issue by ec-davis** [Crestone-Tech/crestone-team#1]
**Story** As a software development company, I want to evaluate some low-cost options for DB hosting so that I can make a good decision in terms of features and price

**Background**
A free postgresql DB on Render.com expires after 1 month. That is okay for early development. That will no longer be okay when we
- have users
- build up significant data that we don't want to risk losing

**Tasks**
evaluate what Render.com offers for DB hosting: 
- [ ] which DB platform(s)
- [ ] price and features at the basic 1-2 tiers
- [ ] find 1-2 competitors and gather the same info
- [ ] produce a spreadsheet/table comparing the options
- [ ] note important details, e.g. do they do backups?

**Acceptance Criteria**
- the table/spreadsheet comparing options lives in our wiki, here: https://github.com/Crestone-Tech/crestone-team/wiki/DB-Hosting:-Features-and-Pricing

Each row shows the 

- provider, e.g. Render.com
- url to info about the db hosting, e.g. https://render.com/pricing
- db type, e.g. postgresql
- name of the service tier, e.g. "Free", "Starter"
- price
- other details. Use your judgment... what's important?
