### ISSUE TITLE
Application hosting: what do we need and what will it cost?

### ISSUE THREAD

**Issue by crestonesoftware** [Crestone-Tech/crestone-team#2]
Story As a software development company, I want to evaluate some low-cost options, for hosting our projects, so that I can make a good decision in terms of features and price

**Background**
Render.com provides free site hosting for web services. Is that good enough for our purposes?

- will it host a React app with Express backend? (Greentrail)
- what are the downsides of the free tier?
- what would push us toward upgrading? e.g. if we have users, the startup delay when the app goes to sleep will probably not be okay

**Tasks**

- [ ] research the questions above, for Render
- [ ] find out the price and any standout features at the basic tier
- [ ] find 1-2 competitors and gather the same info
- [ ] produce a spreadsheet/table comparing the options

**Acceptance Criteria**

The table/spreadsheet comparing options lives in our wiki, here: https://github.com/Crestone-Tech/crestone-team/wiki/DB-Hosting:-Features-and-Pricing
Each row shows the

- provider, e.g. Render.com
- url to info about the hosting, e.g. https://render.com/pricing
- name of the service tier, e.g. "Free", "Starter"
- price
- does it fit Greentrail's technical needs?
- does it fit Travel Buddy's technical needs?
- other details that catch your eye. What's important?
